name: .NET CI/CD

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  DOTNET_VERSION: '8.0.x'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Setup .NET
    - uses: actions/setup-dotnet@v
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Restore dependencies
    - run: dotnet restore SimpleCICD.sln

    - name: Build solution
    - run: dotnet build SimpleCICD.sln --configuration Release --no-restore

    - name: Run Tests
    - run: dotnet test ./src/WebApi.Tests/WebApi.Tests.csproj

  test:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
    - uses: actions/checkout@v4

    - name: Setup .NET
    - uses: actions/setup-dotnet@v
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}

    - name: Run Tests
    - run: dotnet test ./src/WebApi.Tests/WebApi.Tests.csproj
    
